apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics_app
  labels:
    app: metrics_app
spec:
  selector:
    matchLabels:
      app: metrics_app
  replicas: 3
  template:
   metadata:
    labels:
     app: metrics_app
   spec:
    containers:
    - name: nginx
      image:  yanivomc/metrics_app
      ports:
      - containerPort: 8080


