apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingresspath
spec:
  ingressClassName: nginx
  rules:
  - host: bear..nip.io
    http:
      paths:
      - path: /bear(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: bearsvc
            port:
              number: 80
  - host: moose..nip.io
    http:
      paths:
      - path: /moose(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: moosesvc
            port:
              number: 80
