apiVersion: v1 
kind: Pod  
metadata: 
 name: multi-pod
spec:
 containers: 
 - name: alpha
   image: nginx
 - name: beta
   image: busybox
   command:
     - "sleep"
     - "4800"  
   env: 
   - name: ALPHA
     value: "container1"
   - name: BETA
     value: "container2"