apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
    env: prod
spec:
  containers:
  - name: mysql
    image: nginx
######
apiVersion: v1
kind: Pod
metadata:
  name: redisapp
  labels:
    app: redisapp
    env: prod
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mysql
        topologyKey: kubernetes.io/hostname
  containers:
   - name: redis
     image: nginx

#######
apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: web
    env: prod
spec:
  affinity:
   podAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     - labelSelector:
         matchExpressions:
         - key: app
           operator: In
           values:
           - redisapp
       topologyKey: kubernetes.io/hostname

  containers:
   - name: webapp
     image: nginx


