apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: web
    env: prod
spec:
  affinity:
   podAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
     - labelSelector:
         matchExpressions:
         - key: app
           operator: In
           values:
           - redisapp
       topologyKey: kubernetes.io/hostname

  containers:
   - name: webapp
     image: nginx


