apiVersion: apps/v1
kind: Deployment
metadata:
  name: beardeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bear
  template:
    metadata:
      labels:
        app: bear
        sel: hear-bear
    spec:
      containers:
      - name: bear
        image: supergiantkir/animals:bear
        ports:
        - containerPort: 80
