apiVersion: v1
kind: Service
metadata:
  name: canaryservice
  labels:
    sel: near-bear
spec:
  selector:
    sel: hear-bear
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer    
