apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY1
          valueFrom:
            configMapKeyRef:
              name: keyvalcfgmap
              key: key1
      env:
        - name: SPECIAL_LEVEL_KEY2
          valueFrom:
            configMapKeyRef:
              name: keyvalcfgmap
              key: key2
  restartPolicy: Never 