kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
spec:
  selector:
    app: music
  type: {{ .Values.type }}
  ports:         
  - name: http
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
