apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ing
  labels:
  {{- include "spring.labels" . | nindent 4}}
spec:
  ingressClassName: nginx
  rules:
    - http:
       paths:
        - path: /
          pathType: Prefix

          backend:
            service:
              name: {{ .Release.Name }}-svc
              port:
                 number: {{ .Values.port }}
~                                                                                                                                                                                    
~                                               
