kind: Service
apiVersion: v1     
metadata:
  {{- include "spring.labels" . | nindent 2}}
spec:
  selector:
    app: music
    {{- include "spring.labels" . | nindent 4}}
  type: {{ .Values.type }}
  ports:         
  - name: {{ .Values.portName }}
    protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}

