apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "5"
    deployment.kubernetes.io/max-replicas: "7"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-12-10T16:59:31Z"
  generation: 1
  labels:
    app: webapp
    pod-template-hash: 6684ccd7b8
  name: webapp-6684ccd7b8
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: webapp
    uid: a8210232-86b4-44ca-a22e-804386ab8223
  resourceVersion: "991408"
  uid: 8a7d5ec5-2bd4-4bac-a984-63f277db43cd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
      pod-template-hash: 6684ccd7b8
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
        pod-template-hash: 6684ccd7b8
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  fullyLabeledReplicas: 5
  observedGeneration: 1
  readyReplicas: 5
  replicas: 5
