apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2pod-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      env: prod
  replicas: 2
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx