apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3pod-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      env: dev
  replicas: 3
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: nginx
        image: nginx