apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: use-pv
  name: use-pvspec-alvadim
  containers:
  - image: nginx
    name: use-pv
    resources: {}
    volumeMounts:
    - name: pv-1
      mountPath: /data  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

  volumes:
  - name: pv-1
     persistentVolumeClaim:
     ClaimName: pv-claim