apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resolver
spec:
  selector:
    matchLabels:
      app: nginx-resolver
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-resolver
    spec:
      containers:
      - name: hello
        image: nginx
        ports:
        - containerPort: 8080
...
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ndinx-resolver